Repository trungleduc/ipyflex, pull requests merged in 2021-12, with the labels that each got.

#21 Add header component
  css/application.css
  css/buttons.css
  css/widget.css
  ipyflex/flex_layout.py
  ipyflex/utils.py
  src/dialogWidget.tsx
  src/headerComponent.tsx
  src/icons.tsx
  src/reactWidget.tsx
  src/utils.tsx
  src/widget.tsx
Labels: enhancement, UI

#19 Add Jupyter releaser
  .github/workflows/check_release.yaml
  CHANGELOG.md
  LICENSE
  MANIFEST.in
  ipyflex/_version.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#27 Add `galata` UI tests
  .github/workflows/ui-tests.yml
  .gitignore
  setup.py
  ui-tests/jupyter_server_config.py
  ui-tests/notebooks/CustomHeader.ipynb
  ui-tests/notebooks/CustomStyle.ipynb
  ui-tests/notebooks/DashboardWithHeader.ipynb
  ui-tests/notebooks/EmptyDashboard.ipynb
  ui-tests/notebooks/MultipleSections.ipynb
  ui-tests/notebooks/PlaceholderWidgets.ipynb
  ui-tests/notebooks/WithWidgets.ipynb
  ui-tests/notebooks/WithWidgetsFactory.ipynb
  ui-tests/notebooks/multiplesections.json
  ui-tests/notebooks/placeholderwidgets.json
  ui-tests/notebooks/withwidgetfactory.json
  ui-tests/notebooks/withwidgets.json
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/ipyflex.test.ts
  ui-tests/tests/ipyflex.test.ts-snapshots/CustomHeader-linux.png
  ui-tests/tests/ipyflex.test.ts-snapshots/CustomStyle-linux.png
  ui-tests/tests/ipyflex.test.ts-snapshots/DashboardWithHeader-linux.png
  ui-tests/tests/ipyflex.test.ts-snapshots/EmptyDashboard-linux.png
  ui-tests/tests/ipyflex.test.ts-snapshots/MultipleSections-linux.png
  ui-tests/tests/ipyflex.test.ts-snapshots/PlaceholderWidgets-linux.png
  ui-tests/tests/ipyflex.test.ts-snapshots/WithWidgets-linux.png
  ui-tests/tests/ipyflex.test.ts-snapshots/WithWidgetsFactory-linux.png
  ui-tests/yarn.lock
Labels: maintenance, testing

#10 ipyvuetify examples
  examples/withipyvuetify/vue_example.json
  examples/withipyvuetify/withipyvuetify.ipynb
Labels: documentation

#29 Add api to save/load template from python side.
  .github/workflows/build.yml
  ipyflex/__init__.py
  ipyflex/flex_layout.py
  ipyflex/utils.py
  src/menuWidget.tsx
  src/reactWidget.tsx
  src/utils.tsx
Labels: enhancement

#32 Update non-editable mode
  src/defaultModelFactory.ts
  src/reactWidget.tsx
Labels: enhancement
